#!/usr/bin/expect
set timeout -1
set user [lindex $argv 0]
set passwd [lindex $argv 1]

spawn git push
expect {
        "*Username*" { send "$user\n"}
	"*Password*" { send "$passwd\n"}
        "*#" {
        send_user "[exec echo \"scp : Something is wrong\"]"
        exit  }
}
expect {
        "*Username*" { send "$user\n"}
        "*Password*" { send "$passwd\n"}
        "*#" {
        send_user "[exec echo \"scp : Something is wrong\"]"
        exit  }
}

expect eof

